//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryControl.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InventoryControl.Application.Resources.ResourceMessages", typeof(ResourceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número da página deve ser maior que zero..
        /// </summary>
        public static string PAGE_NUMBER_GREATER_THAN_ZERO {
            get {
                return ResourceManager.GetString("PAGE_NUMBER_GREATER_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho da página deve ser maior que zero..
        /// </summary>
        public static string PAGE_SIZE_GREATER_THAN_ZERO {
            get {
                return ResourceManager.GetString("PAGE_SIZE_GREATER_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um produto com esse nome já existe..
        /// </summary>
        public static string PRODUCT_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("PRODUCT_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição do produto não deve exceder 1000 caracteres..
        /// </summary>
        public static string PRODUCT_DESCRIPTION_MAXIMUM_LENGTH {
            get {
                return ResourceManager.GetString("PRODUCT_DESCRIPTION_MAXIMUM_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id inválido..
        /// </summary>
        public static string PRODUCT_ID_INVALID {
            get {
                return ResourceManager.GetString("PRODUCT_ID_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do produto não deve exceder 100 caracteres..
        /// </summary>
        public static string PRODUCT_NAME_MAXIMUM_LENGTH {
            get {
                return ResourceManager.GetString("PRODUCT_NAME_MAXIMUM_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do produto deve conter pelo menos 2 caracteres..
        /// </summary>
        public static string PRODUCT_NAME_MINIMUM_LENGTH {
            get {
                return ResourceManager.GetString("PRODUCT_NAME_MINIMUM_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do produto é obrigatório..
        /// </summary>
        public static string PRODUCT_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("PRODUCT_NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O preço deve ser maior que zero..
        /// </summary>
        public static string PRODUCT_PRICE_GREATER_THAN_ZERO {
            get {
                return ResourceManager.GetString("PRODUCT_PRICE_GREATER_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A quantidade deve ser maior que zero..
        /// </summary>
        public static string QUANTITY_GREATER_THAN_ZERO {
            get {
                return ResourceManager.GetString("QUANTITY_GREATER_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O termo de pesquisa não pode exceder 100 caracteres..
        /// </summary>
        public static string SEARCH_TERM_MAX_LENGTH {
            get {
                return ResourceManager.GetString("SEARCH_TERM_MAX_LENGTH", resourceCulture);
            }
        }
    }
}
